create table "PRS".EMPLOYEE
(
	USERNAME VARCHAR(255) not null primary key,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	IC_PASSPORT_NO VARCHAR(255),
	EMAIL VARCHAR(255),
	AGE INTEGER,
	PASSWORD VARCHAR(255),
	ALLOWANCE DOUBLE,
	BASIC_SALARY DOUBLE,
	POSITION VARCHAR(255),
	EMPLOYEE_ID VARCHAR(255),
    	ROLE VARCHAR(255)
)